version: '2'
services:
  redis:
    image: redis
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      args:
        LITA_ENV: development
    volumes:
      - ./:/app
    environment:
      - "LITA_ENV=development"
      - "REDIS_HOST=redis"
    links:
      - redis:redis
    ports:
      - 80:3000
